name: 03-2 Fetch Key Vault Secret

on:
  workflow_dispatch:

jobs:
  fetch_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch secret from Key Vault
        id: secret
        run: |
          secret_value=$(az keyvault secret show --name credentials --vault-name frasersvault --query 'value' -o tsv)
          echo "::set-output name=secret_value::$secret_value"

      - name: Append secret to file
        run: |
          echo "${{ steps.secret.outputs.secret_value }}" >> ./secret.txt
          echo "$(<./secret.txt )"
          
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts-cred
          path: secret.txt
