name: 04- Call Reusable workflow

on: 
 push:
  branches: [main]
  
 workflow_dispatch:
 
jobs:
   call_reusable_workflow:
     uses: anu-01/frasers-gh-actions/.github/workflows/job-dependencies.yml@main
